# Generated by Django 5.2.14 on 2026-05-22 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber', models.ManyToManyField(related_name='subscribers', to=settings.AUTH_USER_MODEL, verbose_name='podpischiki')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='users.userprofile', verbose_name="profil' pol'zovatelya")),
            ],
        ),
    ]
