# Generated by Django 5.2.14 on 2026-06-01 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_username', models.CharField(max_length=100, unique=True, verbose_name='imya polzovatelya v tg')),
                ('tg_chat_id', models.BigIntegerField(unique=True, verbose_name='ID polzovatelya v tg')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='polzovatel')),
            ],
            options={
                'verbose_name': 'Akkauat polzovatelya v tg',
                'verbose_name_plural': " akkaunt' polzavateley v tg",
            },
        ),
    ]
