# Generated by Django 5.2.14 on 2026-06-08 11:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TelegramUser',
            new_name='TelegramBotUser',
        ),
    ]
