# Generated by Django 5.2.12 on 2026-04-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homesslider',
            options={'verbose_name': 'foto claydera', 'verbose_name_plural': 'fotki claydera'},
        ),
        migrations.AlterField(
            model_name='homesslider',
            name='image',
            field=models.ImageField(upload_to='home/slider/', verbose_name='foto'),
        ),
    ]
