# Generated by Django 5.2.12 on 2026-04-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_homesslider_options_alter_homesslider_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createed_at', models.DateField(auto_now=True, verbose_name='Data cozdaniya')),
                ('updated_at', models.DateField(auto_now_add=True, verbose_name='Data izmeneniya')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nazvaniye')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name="Korotkaya cc'lka")),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivna')),
            ],
            options={
                'verbose_name': 'kategoriya',
                'verbose_name_plural': 'Kategorii',
            },
        ),
    ]
