# Generated by Django 5.2.12 on 2026-04-11 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='createed_at',
            new_name='created_at',
        ),
    ]
