# Generated by Django 5.2.12 on 2026-04-15 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_createed_at_category_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True, verbose_name='Data cozdaniya')),
                ('updated_at', models.DateField(auto_now_add=True, verbose_name='Data izmeneniya')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='nazvaniye')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Slag')),
                ('short_descriptions', models.TextField(verbose_name='Kratkoe opisaniye')),
                ('full_descriptions', models.TextField(blank=True, null=True, verbose_name='polnoye opisaniye')),
                ('previes', models.ImageField(upload_to='media/previews/%y/%m/%d', verbose_name="prev'iyu")),
                ('views_quantity', models.IntegerField(default=0, verbose_name='Kol-vo prosmotrov')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivna')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Kategoriya')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="pol'zovatel'")),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
