# Generated by Django 5.2.12 on 2026-04-15 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='previes',
            new_name='preview',
        ),
    ]
