# Generated by Django 5.2.12 on 2026-04-16 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_category_post_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='full_descriptions',
            new_name='full_description',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='short_descriptions',
            new_name='short_description',
        ),
    ]
