# Generated by Django 5.2.12 on 2026-04-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_full_descriptions_post_full_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preview',
            field=models.ImageField(upload_to='previews/%y/%m/%d', verbose_name="prev'iyu"),
        ),
    ]
