# Generated by Django 5.2.12 on 2026-04-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_post_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data cozdaniya'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data cozdaniya'),
        ),
        migrations.AlterField(
            model_name='post',
            name='preview',
            field=models.ImageField(upload_to='media/previews/%y/%m/%d', verbose_name="prev'iyu"),
        ),
    ]
