# Generated by Django 5.2.12 on 2026-04-28 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_category_created_at_alter_post_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='kommentariy')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data sozdaniya')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data izmeneniya')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statiya', to='main.post', verbose_name='post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name="pol'zovatel'")),
            ],
            options={
                'verbose_name': 'kommentariy posta',
                'verbose_name_plural': 'Kommentarii postov',
            },
        ),
    ]
