# Generated by Django 5.2.12 on 2026-05-02 12:36

import apps.main.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_postcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data cozdaniya')),
                ('updated_at', models.DateField(auto_now_add=True, verbose_name='Data izmeneniya')),
                ('image', models.ImageField(upload_to=apps.main.models.make_post_image_path, verbose_name='foto')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.post', verbose_name='post')),
            ],
            options={
                'verbose_name': 'foto post',
                'verbose_name_plural': 'foto posts',
            },
        ),
    ]
