# Generated by Django 5.2.14 on 2026-05-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_postdislike_postlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data cozdaniya')),
                ('updated_at', models.DateField(auto_now_add=True, verbose_name='Data izmeneniya')),
                ('question', models.CharField(max_length=100, verbose_name='vopros')),
                ('answer', models.TextField(verbose_name='otvet')),
            ],
            options={
                'verbose_name': 'vopros-otvet',
                'verbose_name_plural': "vopros'-otveti",
            },
        ),
    ]
